### ISSUE TITLE
Settings page initial selected tab

### ISSUE THREAD

**Issue by andrewctam** [sbu-416-24sp/orcanet-desktop#18]
When opening the Settings page, no tab is selected by default. I thought this was due to some error with the backend, but it was because no tab was selected.  I think it makes sense to have "Transfer" selected by default.

<img width="861" alt="image" src="https://github.com/sbu-416-24sp/orcanet-desktop/assets/54547089/0390d735-8d8c-463e-a632-12589850fb31">

**Comment by Adamlip1334** [comment]
I agree that transfer should be selected by default. I created a pr #20 with the change. I recall that transfer page was always selected by default until a change was made to it yesterday. Would like to hear from someone who worked on settings page to see if that change was intended.

**Comment by xiej2520** [comment]
Agreed, transfer was initially selected when I was testing it before.
